// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package eventx

import (
	"context"
	"sync"
)

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
// 	func TestSomethingThatUsesRepository(t *testing.T) {
//
// 		// make and configure a mocked Repository
// 		mockedRepository := &RepositoryMock{
// 			GetLastEventsFunc: func(ctx context.Context, limit uint64) ([]Event, error) {
// 				panic("mock out the GetLastEvents method")
// 			},
// 			GetUnprocessedEventsFunc: func(ctx context.Context, limit uint64) ([]Event, error) {
// 				panic("mock out the GetUnprocessedEvents method")
// 			},
// 			UpdateSequencesFunc: func(ctx context.Context, events []Event) error {
// 				panic("mock out the UpdateSequences method")
// 			},
// 		}
//
// 		// use mockedRepository in code that requires Repository
// 		// and then make assertions.
//
// 	}
type RepositoryMock struct {
	// GetLastEventsFunc mocks the GetLastEvents method.
	GetLastEventsFunc func(ctx context.Context, limit uint64) ([]Event, error)

	// GetUnprocessedEventsFunc mocks the GetUnprocessedEvents method.
	GetUnprocessedEventsFunc func(ctx context.Context, limit uint64) ([]Event, error)

	// UpdateSequencesFunc mocks the UpdateSequences method.
	UpdateSequencesFunc func(ctx context.Context, events []Event) error

	// calls tracks calls to the methods.
	calls struct {
		// GetLastEvents holds details about calls to the GetLastEvents method.
		GetLastEvents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit uint64
		}
		// GetUnprocessedEvents holds details about calls to the GetUnprocessedEvents method.
		GetUnprocessedEvents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit uint64
		}
		// UpdateSequences holds details about calls to the UpdateSequences method.
		UpdateSequences []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Events is the events argument value.
			Events []Event
		}
	}
	lockGetLastEvents        sync.RWMutex
	lockGetUnprocessedEvents sync.RWMutex
	lockUpdateSequences      sync.RWMutex
}

// GetLastEvents calls GetLastEventsFunc.
func (mock *RepositoryMock) GetLastEvents(ctx context.Context, limit uint64) ([]Event, error) {
	callInfo := struct {
		Ctx   context.Context
		Limit uint64
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockGetLastEvents.Lock()
	mock.calls.GetLastEvents = append(mock.calls.GetLastEvents, callInfo)
	mock.lockGetLastEvents.Unlock()
	if mock.GetLastEventsFunc == nil {
		var (
			eventsOut []Event
			errOut    error
		)
		return eventsOut, errOut
	}
	return mock.GetLastEventsFunc(ctx, limit)
}

// GetLastEventsCalls gets all the calls that were made to GetLastEvents.
// Check the length with:
//     len(mockedRepository.GetLastEventsCalls())
func (mock *RepositoryMock) GetLastEventsCalls() []struct {
	Ctx   context.Context
	Limit uint64
} {
	var calls []struct {
		Ctx   context.Context
		Limit uint64
	}
	mock.lockGetLastEvents.RLock()
	calls = mock.calls.GetLastEvents
	mock.lockGetLastEvents.RUnlock()
	return calls
}

// GetUnprocessedEvents calls GetUnprocessedEventsFunc.
func (mock *RepositoryMock) GetUnprocessedEvents(ctx context.Context, limit uint64) ([]Event, error) {
	callInfo := struct {
		Ctx   context.Context
		Limit uint64
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockGetUnprocessedEvents.Lock()
	mock.calls.GetUnprocessedEvents = append(mock.calls.GetUnprocessedEvents, callInfo)
	mock.lockGetUnprocessedEvents.Unlock()
	if mock.GetUnprocessedEventsFunc == nil {
		var (
			eventsOut []Event
			errOut    error
		)
		return eventsOut, errOut
	}
	return mock.GetUnprocessedEventsFunc(ctx, limit)
}

// GetUnprocessedEventsCalls gets all the calls that were made to GetUnprocessedEvents.
// Check the length with:
//     len(mockedRepository.GetUnprocessedEventsCalls())
func (mock *RepositoryMock) GetUnprocessedEventsCalls() []struct {
	Ctx   context.Context
	Limit uint64
} {
	var calls []struct {
		Ctx   context.Context
		Limit uint64
	}
	mock.lockGetUnprocessedEvents.RLock()
	calls = mock.calls.GetUnprocessedEvents
	mock.lockGetUnprocessedEvents.RUnlock()
	return calls
}

// UpdateSequences calls UpdateSequencesFunc.
func (mock *RepositoryMock) UpdateSequences(ctx context.Context, events []Event) error {
	callInfo := struct {
		Ctx    context.Context
		Events []Event
	}{
		Ctx:    ctx,
		Events: events,
	}
	mock.lockUpdateSequences.Lock()
	mock.calls.UpdateSequences = append(mock.calls.UpdateSequences, callInfo)
	mock.lockUpdateSequences.Unlock()
	if mock.UpdateSequencesFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateSequencesFunc(ctx, events)
}

// UpdateSequencesCalls gets all the calls that were made to UpdateSequences.
// Check the length with:
//     len(mockedRepository.UpdateSequencesCalls())
func (mock *RepositoryMock) UpdateSequencesCalls() []struct {
	Ctx    context.Context
	Events []Event
} {
	var calls []struct {
		Ctx    context.Context
		Events []Event
	}
	mock.lockUpdateSequences.RLock()
	calls = mock.calls.UpdateSequences
	mock.lockUpdateSequences.RUnlock()
	return calls
}
